all_watched_anime = [
    "Afro Samurai",
    "Attack on Titan",
    "Ayakashi: Japanese Classic Horror",
    "Banana Fish",
    "Beastars",
    "Beyblade",
    "Black Butler",
    "Kuroshitsuji",
    "Black Clover",
    "Black Lagoon",
    "Bungo Stray Dogs",
    "Cardcaptor Sakura",
    "Chainsaw Man",
    "Code Geass",
    "Cowboy Bebop",
    "Cyberpunk: Edgerunners",
    "Dan Da Dan",
    "Death Note",
    "Delicious in Dungeon",
    "Demon Slayer",
    "Kimetsu no Yaiba",
    "Digimon",
    "Dororo",
    "Dorohedoro",
    "Dr. Stone",
    "Dungeon Meshi",
    "Ergo Proxy",
    "Food Wars",
    "Frieren",
    "Fullmetal Alchemist: Brotherhood",
    "Fullmetal Alchemist",
    "Fruits Basket",
    "Gintama",
    "Grand Blue",
    "Great Pretender",
    "Horimiya",
    "Hori-san to Miyamura-kun",
    "Itou Junji",
    "JoJo's Bizarre Adventure",
    "Jujutsu Kaisen",
    "Junji Ito Collection",
    "Junji Ito Maniac: Japanese Tales of the Macabre",
    "Kakegurui",
    "Kimi ni Todoke",
    "Link Click",
    "Made in Abyss",
    "Mashle: Magic and Muscles",
    "Mononoke",
    "Mushishi",
    "Mushi-shi",
    "Youjo Shenki",
    "Naruto",
    "One Piece",
    "Ouran High School Host Club",
    "Parasyte",
    "Psycho-Pass",
    "Ramen Akaneko",
    "Saga of Tanya the Evil",
    "Shangri-La Frontier",
    "Solo Leveling",
    "Spy x Family",
    "Summer Time Rendering",
    "Sword Art Online",
    "The Tatami Galaxy",
    "The Tatami Time Machine Blues",
    "The Way of the Househusband",
    "The Witch and the Beast",
    "Tokyo Ghoul",
    "Uncle from Another World",
    "Yasuke",
]
